num1 = int(input("Insira o primeiro número inteiro: "))
num2 = int(input("Insira o segundo número inteiro: "))
#print("Você inseriu os números:", numero1, "e", numero2)
print(f"A soma dos dois valores é : {num1+num2}")
print(f"A multiplicação dos produtos é : {num1*num2}")